export type ElementConfig = {
  name: string;
  symbol: string;
  protons: number;
  neutrons: number;
  shells: number[];
  atomicWeight: string;
  electronConfiguration: string;
  title: string;
  description: string;
};

export const elements: ElementConfig[] = [
  {
    name: "Hydrogen",
    symbol: "H",
    protons: 1,
    neutrons: 0,
    shells: [1],
    atomicWeight: "1.008",
    electronConfiguration: "1s¹",
    title: "Hydrogen (H) - The Simplest Element",
    description:
      "Hydrogen is the simplest and most abundant element in the universe, making up about 75% of its mass. It's a key component of water and all organic matter. Under standard conditions, it's a colorless, odorless, and flammable gas.",
  },
  {
    name: "Helium",
    symbol: "He",
    protons: 2,
    neutrons: 2,
    shells: [2],
    atomicWeight: "4.0026",
    electronConfiguration: "1s²",
    title: "Helium (He) - The Noble Gas",
    description:
      "Helium is the second-lightest element. It's a noble gas, meaning it is chemically inert. Famously used to fill balloons and airships, it is also crucial in cryogenics for cooling superconducting magnets, such as in MRI scanners.",
  },
  {
    name: "Lithium",
    symbol: "Li",
    protons: 3,
    neutrons: 4,
    shells: [2, 1],
    atomicWeight: "6.94",
    electronConfiguration: "[He] 2s¹",
    title: "Lithium (Li) - The Lightest Metal",
    description:
      "Lithium is a soft, silvery-white alkali metal. It is the lightest metal and the least dense solid element. Highly reactive and flammable, it is primarily used in rechargeable batteries for mobile phones, laptops, and electric vehicles.",
  },
  {
    name: "Beryllium",
    symbol: "Be",
    protons: 4,
    neutrons: 5,
    shells: [2, 2],
    atomicWeight: "9.0122",
    electronConfiguration: "[He] 2s²",
    title: "Beryllium (Be) - The Gemstone Metal",
    description:
      "Beryllium is a relatively rare, lightweight, and strong steel-gray metal. It enhances the properties of many alloys and is used in aerospace, defense, and medical applications. It is found in gemstones like beryl (aquamarine, emerald).",
  },
  {
    name: "Boron",
    symbol: "B",
    protons: 5,
    neutrons: 6,
    shells: [2, 3],
    atomicWeight: "10.81",
    electronConfiguration: "[He] 2s² 2p¹",
    title: "Boron (B) - The Versatile Metalloid",
    description:
      "Boron is a metalloid with several forms, the most common being amorphous boron, a dark powder. It's known for its hardness and is used in fiberglass, heat-resistant glass (borosilicate), and as a dopant in the semiconductor industry.",
  },
  {
    name: "Carbon",
    symbol: "C",
    protons: 6,
    neutrons: 6,
    shells: [2, 4],
    atomicWeight: "12.011",
    electronConfiguration: "[He] 2s² 2p²",
    title: "Carbon (C) - The Backbone of Life",
    description:
      "Carbon is the chemical basis for all known life. It can form a vast number of compounds, more than any other element. Its most famous allotropes are diamond, the hardest natural substance, and graphite, used in pencils and lubricants.",
  },
  {
    name: "Nitrogen",
    symbol: "N",
    protons: 7,
    neutrons: 7,
    shells: [2, 5],
    atomicWeight: "14.007",
    electronConfiguration: "[He] 2s² 2p³",
    title: "Nitrogen (N) - The Atmospheric Giant",
    description:
      "Nitrogen makes up about 78% of Earth's atmosphere. As a component of proteins and nucleic acids, it is essential for all living organisms. In liquid form, it's a powerful cryogen, and it's a key ingredient in fertilizers.",
  },
  {
    name: "Oxygen",
    symbol: "O",
    protons: 8,
    neutrons: 8,
    shells: [2, 6],
    atomicWeight: "15.999",
    electronConfiguration: "[He] 2s² 2p⁴",
    title: "Oxygen (O) - The Breath of Life",
    description:
      "Oxygen is a highly reactive nonmetal essential for respiration in most terrestrial life. It is the third most abundant element in the universe and the most abundant by mass in the Earth's crust, mainly in oxides.",
  },
  {
    name: "Fluorine",
    symbol: "F",
    protons: 9,
    neutrons: 10,
    shells: [2, 7],
    atomicWeight: "18.998",
    electronConfiguration: "[He] 2s² 2p⁵",
    title: "Fluorine (F) - The Most Electronegative Element",
    description:
      "Fluorine is a pale yellow, highly corrosive gas. It is the most electronegative and reactive of all elements. It's a key component of many plastics, such as Teflon, and is added to toothpaste and water supplies to prevent tooth decay.",
  },
  {
    name: "Neon",
    symbol: "Ne",
    protons: 10,
    neutrons: 10,
    shells: [2, 8],
    atomicWeight: "20.180",
    electronConfiguration: "[He] 2s² 2p⁶",
    title: "Neon (Ne) - The Glowing Sign",
    description:
      "Neon is a noble gas that is colorless under standard conditions. When an electric current is passed through it, it emits a brilliant reddish-orange glow, which is famously used in advertising signs. It is chemically inert.",
  },
  {
    name: "Sodium",
    symbol: "Na",
    protons: 11,
    neutrons: 12,
    shells: [2, 8, 1],
    atomicWeight: "22.990",
    electronConfiguration: "[Ne] 3s¹",
    title: "Sodium (Na) - The Salty Metal",
    description:
      "Sodium is a soft, silvery-white, highly reactive alkali metal. It is essential for animal life, regulating blood volume and pressure. Its most common compound is sodium chloride (table salt). It's also used in streetlights and as a heat transfer agent.",
  },
  {
    name: "Magnesium",
    symbol: "Mg",
    protons: 12,
    neutrons: 12,
    shells: [2, 8, 2],
    atomicWeight: "24.305",
    electronConfiguration: "[Ne] 3s²",
    title: "Magnesium (Mg) - The Lightweight Strength",
    description:
      "Magnesium is a shiny gray solid and the eighth-most-abundant element in the Earth's crust. It is strong but lightweight, making it ideal for alloys used in cars, aircraft, and electronics. It is also essential for all living cells.",
  },
  {
    name: "Aluminum",
    symbol: "Al",
    protons: 13,
    neutrons: 14,
    shells: [2, 8, 3],
    atomicWeight: "26.982",
    electronConfiguration: "[Ne] 3s² 3p¹",
    title: "Aluminum (Al) - The Everyday Metal",
    description:
      "Aluminum is a silvery-white, lightweight metal. It is not found free in nature but is the most abundant metal in the Earth's crust. Its resistance to corrosion and low density make it vital for transportation, packaging (cans), and construction.",
  },
  {
    name: "Silicon",
    symbol: "Si",
    protons: 14,
    neutrons: 14,
    shells: [2, 8, 4],
    atomicWeight: "28.085",
    electronConfiguration: "[Ne] 3s² 3p²",
    title: "Silicon (Si) - The Digital Age Foundation",
    description:
      "Silicon is a hard, brittle crystalline solid with a blue-gray metallic luster. It is the second most abundant element in the Earth's crust (after oxygen). As a semiconductor, it is the fundamental component of most electronics, including computer chips.",
  },
  {
    name: "Phosphorus",
    symbol: "P",
    protons: 15,
    neutrons: 16,
    shells: [2, 8, 5],
    atomicWeight: "30.974",
    electronConfiguration: "[Ne] 3s² 3p³",
    title: "Phosphorus (P) - The Bearer of Light",
    description:
      "Phosphorus is a highly reactive nonmetal that exists in several forms (white, red, black). It is essential for life, forming the backbone of DNA and RNA. It's widely used in fertilizers, detergents, and, historically, in matches.",
  },
  {
    name: "Sulfur",
    symbol: "S",
    protons: 16,
    neutrons: 16,
    shells: [2, 8, 6],
    atomicWeight: "32.06",
    electronConfiguration: "[Ne] 3s² 3p⁴",
    title: "Sulfur (S) - The Brimstone Element",
    description:
      "Sulfur is a bright yellow, nonmetallic solid. It's known for its distinct smell when burned (as sulfur dioxide). It is essential for life and is a component of two amino acids. Its main use is in the production of sulfuric acid, a key industrial chemical.",
  },
  {
    name: "Chlorine",
    symbol: "Cl",
    protons: 17,
    neutrons: 18,
    shells: [2, 8, 7],
    atomicWeight: "35.45",
    electronConfiguration: "[Ne] 3s² 3p⁵",
    title: "Chlorine (Cl) - The Purifier",
    description:
      "Chlorine is a pale green, highly reactive gas. It is a powerful oxidizing agent used for sanitation and disinfection, particularly in swimming pools and drinking water. It is also a key component of PVC plastic and table salt (NaCl).",
  },
  {
    name: "Argon",
    symbol: "Ar",
    protons: 18,
    neutrons: 22,
    shells: [2, 8, 8],
    atomicWeight: "39.948",
    electronConfiguration: "[Ne] 3s² 3p⁶",
    title: "Argon (Ar) - The Inert Shield",
    description:
      "Argon is the third-most abundant gas in the Earth's atmosphere. As a noble gas, it is inert and colorless. This property makes it useful as a protective atmosphere in welding, electronics manufacturing, and as a fill gas in incandescent light bulbs.",
  },
  {
    name: "Potassium",
    symbol: "K",
    protons: 19,
    neutrons: 20,
    shells: [2, 8, 8, 1],
    atomicWeight: "39.098",
    electronConfiguration: "[Ar] 4s¹",
    title: "Potassium (K) - The Vital Electrolyte",
    description:
      "Potassium is a soft, silvery-white alkali metal that reacts violently with water. It is an essential mineral and electrolyte for human health, crucial for nerve function and muscle contraction. It is also a major component of fertilizers.",
  },
  {
    name: "Calcium",
    symbol: "Ca",
    protons: 20,
    neutrons: 20,
    shells: [2, 8, 8, 2],
    atomicWeight: "40.078",
    electronConfiguration: "[Ar] 4s²",
    title: "Calcium (Ca) - The Builder of Bones",
    description:
      "Calcium is a reactive, silvery-gray alkaline earth metal. It is the most abundant mineral in the human body, essential for strong bones and teeth. It's also vital for muscle function and cell signaling. It is used in cement and mortar.",
  },
  {
    name: "Scandium",
    symbol: "Sc",
    protons: 21,
    neutrons: 24,
    shells: [2, 8, 9, 2],
    atomicWeight: "44.956",
    electronConfiguration: "[Ar] 3d¹ 4s²",
    title: "Scandium (Sc) - The Alloy Enhancer",
    description:
      "Scandium is a silvery-white transition metal. While not abundant, adding small amounts of scandium to aluminum alloys creates materials that are exceptionally strong and lightweight, used in high-performance equipment like bicycle frames and baseball bats.",
  },
  {
    name: "Titanium",
    symbol: "Ti",
    protons: 22,
    neutrons: 26,
    shells: [2, 8, 10, 2],
    atomicWeight: "47.867",
    electronConfiguration: "[Ar] 3d² 4s²",
    title: "Titanium (Ti) - The Strength of the Titans",
    description:
      "Titanium is a transition metal known for its high strength-to-weight ratio and excellent corrosion resistance. It is used in aerospace, medical implants, and sporting goods. Its oxide, titanium dioxide, is a bright white pigment used in paint and sunscreen.",
  },
  {
    name: "Vanadium",
    symbol: "V",
    protons: 23,
    neutrons: 28,
    shells: [2, 8, 11, 2],
    atomicWeight: "50.942",
    electronConfiguration: "[Ar] 3d³ 4s²",
    title: "Vanadium (V) - The Steel Strengthener",
    description:
      "Vanadium is a hard, silvery-gray transition metal. Its primary use is as an additive to steel, creating high-strength steel alloys used in tools, axles, and structural components. Vanadium compounds can exhibit a wide range of beautiful colors.",
  },
  {
    name: "Chromium",
    symbol: "Cr",
    protons: 24,
    neutrons: 28,
    shells: [2, 8, 13, 1],
    atomicWeight: "51.996",
    electronConfiguration: "[Ar] 3d⁵ 4s¹",
    title: "Chromium (Cr) - The Shiny Plating",
    description:
      "Chromium is a hard, shiny, steel-gray metal known for its high polish and tarnish resistance. It is widely used for chrome plating on cars and fixtures. It's also the key ingredient that makes stainless steel 'stainless'.",
  },
  {
    name: "Manganese",
    symbol: "Mn",
    protons: 25,
    neutrons: 30,
    shells: [2, 8, 13, 2],
    atomicWeight: "54.938",
    electronConfiguration: "[Ar] 3d⁵ 4s²",
    title: "Manganese (Mn) - The Unsung Hero of Steel",
    description:
      "Manganese is a hard, brittle, silvery metal. It is too brittle to be used on its own but is essential in the production of iron and steel, where it improves strength, hardness, and durability. It is also an essential trace nutrient for all known living organisms.",
  },
  {
    name: "Iron",
    symbol: "Fe",
    protons: 26,
    neutrons: 30,
    shells: [2, 8, 14, 2],
    atomicWeight: "55.845",
    electronConfiguration: "[Ar] 3d⁶ 4s²",
    title: "Iron (Fe) - The Backbone of Industry",
    description:
      "Iron is the most common element on Earth by mass and the cornerstone of the modern industrial world. It is the main component of steel, the most important construction material. In the body, iron is a key component of hemoglobin, which carries oxygen in the blood.",
  },
  {
    name: "Cobalt",
    symbol: "Co",
    protons: 27,
    neutrons: 32,
    shells: [2, 8, 15, 2],
    atomicWeight: "58.933",
    electronConfiguration: "[Ar] 3d⁷ 4s²",
    title: "Cobalt (Co) - The Blue Pigment",
    description:
      "Cobalt is a hard, lustrous, silvery-blue metal. It is used to create strong, corrosion-resistant alloys and powerful magnets. Its compounds have been used for centuries to create a deep blue color in glass, ceramics, and paints (cobalt blue).",
  },
  {
    name: "Nickel",
    symbol: "Ni",
    protons: 28,
    neutrons: 31,
    shells: [2, 8, 16, 2],
    atomicWeight: "58.693",
    electronConfiguration: "[Ar] 3d⁸ 4s²",
    title: "Nickel (Ni) - The Corrosion Resistor",
    description:
      "Nickel is a silvery-white metal with a slight golden tinge. It is highly resistant to corrosion, making it a key component in stainless steel and other alloys. It is also widely used in coins, batteries, and as a plating material.",
  },
  {
    name: "Copper",
    symbol: "Cu",
    protons: 29,
    neutrons: 35,
    shells: [2, 8, 18, 1],
    atomicWeight: "63.546",
    electronConfiguration: "[Ar] 3d¹⁰ 4s¹",
    title: "Copper (Cu) - The Conductor of Power",
    description:
      "Copper is a soft, malleable, and ductile metal with a characteristic reddish-brown color. Its excellent electrical and thermal conductivity makes it the standard for electrical wiring. It is also used in plumbing, roofing, and alloys like brass and bronze.",
  },
  {
    name: "Zinc",
    symbol: "Zn",
    protons: 30,
    neutrons: 35,
    shells: [2, 8, 18, 2],
    atomicWeight: "65.38",
    electronConfiguration: "[Ar] 3d¹⁰ 4s²",
    title: "Zinc (Zn) - The Sacrificial Protector",
    description:
      "Zinc is a bluish-white metal that is essential for life. Its main application is galvanizing steel—coating it with a layer of zinc to protect it from rust. It's also a component of brass and is used in batteries and dietary supplements.",
  },
  {
    name: "Gallium",
    symbol: "Ga",
    protons: 31,
    neutrons: 39,
    shells: [2, 8, 18, 3],
    atomicWeight: "69.723",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p¹",
    title: "Gallium (Ga) - The Melting Metal",
    description:
      "Gallium is a soft, silvery metal that is famous for its low melting point of 29.76 °C (85.58 °F), which means it will melt in a person's hand. It is a critical component in semiconductors, particularly for manufacturing LEDs (light-emitting diodes).",
  },
  {
    name: "Germanium",
    symbol: "Ge",
    protons: 32,
    neutrons: 41,
    shells: [2, 8, 18, 4],
    atomicWeight: "72.630",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p²",
    title: "Germanium (Ge) - The Infrared Eye",
    description:
      "Germanium is a lustrous, hard, grayish-white metalloid. As a semiconductor, it was a key material in early transistors. Today, it is primarily used in fiber-optic systems and infrared optics, as it is transparent to infrared radiation.",
  },
  {
    name: "Arsenic",
    symbol: "As",
    protons: 33,
    neutrons: 42,
    shells: [2, 8, 18, 5],
    atomicWeight: "74.922",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p³",
    title: "Arsenic (As) - The Poisonous Metalloid",
    description:
      "Arsenic is a metalloid that is notoriously toxic. In its metallic gray form, it is brittle and crystalline. Despite its reputation, it has important uses, such as strengthening alloys and as a key semiconductor in integrated circuits (gallium arsenide).",
  },
  {
    name: "Selenium",
    symbol: "Se",
    protons: 34,
    neutrons: 45,
    shells: [2, 8, 18, 6],
    atomicWeight: "78.971",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁴",
    title: "Selenium (Se) - The Photoconductor",
    description:
      "Selenium is a nonmetal with properties that are intermediate between sulfur and tellurium. Its electrical conductivity changes with light exposure, a property used in photocells and early photocopiers. It is also an essential trace nutrient for animals.",
  },
  {
    name: "Bromine",
    symbol: "Br",
    protons: 35,
    neutrons: 45,
    shells: [2, 8, 18, 7],
    atomicWeight: "79.904",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁵",
    title: "Bromine (Br) - The Liquid Halogen",
    description:
      "Bromine is a fuming reddish-brown liquid at room temperature, the only halogen to be so. It is highly reactive and corrosive. Bromine compounds are used as flame retardants, in water purification, and in pharmaceuticals.",
  },
  {
    name: "Krypton",
    symbol: "Kr",
    protons: 36,
    neutrons: 48,
    shells: [2, 8, 18, 8],
    atomicWeight: "83.798",
    electronConfiguration: "[Ar] 3d¹⁰ 4s² 4p⁶",
    title: "Krypton (Kr) - The Hidden Gas",
    description:
      "Krypton is a colorless, odorless, noble gas. Its name comes from the Greek word 'kryptos', meaning 'hidden'. It is used with other gases in fluorescent lamps and high-speed photography flashes. For a time, the meter was officially defined by one of its spectral lines.",
  },
  {
    name: "Rubidium",
    symbol: "Rb",
    protons: 37,
    neutrons: 48,
    shells: [2, 8, 18, 8, 1],
    atomicWeight: "85.468",
    electronConfiguration: "[Kr] 5s¹",
    title: "Rubidium (Rb) - The Atomic Clock Component",
    description:
      "Rubidium is a soft, silvery-white alkali metal that is highly reactive, capable of igniting spontaneously in air. It is used in specialized vacuum tubes and is a key component in atomic clocks, which are the most accurate timekeeping devices known.",
  },
  {
    name: "Strontium",
    symbol: "Sr",
    protons: 38,
    neutrons: 50,
    shells: [2, 8, 18, 8, 2],
    atomicWeight: "87.62",
    electronConfiguration: "[Kr] 5s²",
    title: "Strontium (Sr) - The Red Firework",
    description:
      "Strontium is a soft, silvery-white alkaline earth metal that turns yellow when exposed to air. It is best known for the brilliant crimson color its salts impart to flames, making it a common ingredient in fireworks and signal flares.",
  },
  {
    name: "Yttrium",
    symbol: "Y",
    protons: 39,
    neutrons: 50,
    shells: [2, 8, 18, 9, 2],
    atomicWeight: "88.906",
    electronConfiguration: "[Kr] 4d¹ 5s²",
    title: "Yttrium (Y) - The Red Phosphor",
    description:
      "Yttrium is a silvery-metallic transition metal. It is most famously used in red phosphors, such as those that produced the color in older CRT television screens. It is also used in lasers, superconductors, and as an alloy additive.",
  },
  {
    name: "Zirconium",
    symbol: "Zr",
    protons: 40,
    neutrons: 51,
    shells: [2, 8, 18, 10, 2],
    atomicWeight: "91.224",
    electronConfiguration: "[Kr] 4d² 5s²",
    title: "Zirconium (Zr) - The Nuclear Metal",
    description:
      "Zirconium is a lustrous, grayish-white transition metal that is highly resistant to corrosion. Because it does not readily absorb neutrons, it is widely used in nuclear reactors as cladding for fuel rods. Its oxide forms the gemstone substitute, cubic zirconia.",
  },
  {
    name: "Niobium",
    symbol: "Nb",
    protons: 41,
    neutrons: 52,
    shells: [2, 8, 18, 12, 1],
    atomicWeight: "92.906",
    electronConfiguration: "[Kr] 4d⁴ 5s¹",
    title: "Niobium (Nb) - The Superconducting Alloy",
    description:
      "Niobium is a light gray, crystalline, and ductile transition metal. It is used in various superalloys, especially those needing heat resistance, for jet engines. Niobium-based alloys are also important superconductors, used in MRI magnets.",
  },
  {
    name: "Molybdenum",
    symbol: "Mo",
    protons: 42,
    neutrons: 54,
    shells: [2, 8, 18, 13, 1],
    atomicWeight: "95.96",
    electronConfiguration: "[Kr] 4d⁵ 5s¹",
    title: "Molybdenum (Mo) - The High-Temperature Metal",
    description:
      "Molybdenum is a silvery-gray metal with one of the highest melting points of all elements. This property makes it essential for creating high-strength steel alloys that can withstand high temperatures and pressures, used in machinery and military armor.",
  },
  {
    name: "Technetium",
    symbol: "Tc",
    protons: 43,
    neutrons: 55,
    shells: [2, 8, 18, 13, 2],
    atomicWeight: "98",
    electronConfiguration: "[Kr] 4d⁵ 5s²",
    title: "Technetium (Tc) - The First Artificial Element",
    description:
      "Technetium is the lightest element whose isotopes are all radioactive. It was the first element to be produced artificially. Its most stable isotope, technetium-99m, is a widely used radioactive tracer in medical diagnostic procedures.",
  },
  {
    name: "Ruthenium",
    symbol: "Ru",
    protons: 44,
    neutrons: 57,
    shells: [2, 8, 18, 15, 1],
    atomicWeight: "101.07",
    electronConfiguration: "[Kr] 4d⁷ 5s¹",
    title: "Ruthenium (Ru) - The Hardening Catalyst",
    description:
      "Ruthenium is a rare transition metal belonging to the platinum group. It is used as a hardener for platinum and palladium alloys, making them more wear-resistant for things like electrical contacts. It is also a versatile catalyst.",
  },
  {
    name: "Rhodium",
    symbol: "Rh",
    protons: 45,
    neutrons: 58,
    shells: [2, 8, 18, 16, 1],
    atomicWeight: "102.91",
    electronConfiguration: "[Kr] 4d⁸ 5s¹",
    title: "Rhodium (Rh) - The Precious Catalyst",
    description:
      "Rhodium is a silvery-white, hard, and corrosion-resistant noble metal. It is one of the rarest and most valuable precious metals. Its main use is as a catalyst in the catalytic converters of automobiles to clean up exhaust emissions.",
  },
  {
    name: "Palladium",
    symbol: "Pd",
    protons: 46,
    neutrons: 60,
    shells: [2, 8, 18, 18],
    atomicWeight: "106.42",
    electronConfiguration: "[Kr] 4d¹⁰",
    title: "Palladium (Pd) - The Hydrogen Sponge",
    description:
      "Palladium is a rare, silvery-white metal in the platinum group. Like rhodium, it is a vital catalyst in catalytic converters. It has the unusual ability to absorb up to 900 times its own volume of hydrogen gas, a property studied for hydrogen storage.",
  },
  {
    name: "Silver",
    symbol: "Ag",
    protons: 47,
    neutrons: 61,
    shells: [2, 8, 18, 18, 1],
    atomicWeight: "107.87",
    electronConfiguration: "[Kr] 4d¹⁰ 5s¹",
    title: "Silver (Ag) - The Reflective Conductor",
    description:
      "Silver is a precious metal known for its brilliant white luster. It has the highest electrical and thermal conductivity of any metal. It is used in jewelry, tableware, coins, and high-quality electrical contacts. Silver compounds are also light-sensitive, forming the basis of traditional photography.",
  },
  {
    name: "Cadmium",
    symbol: "Cd",
    protons: 48,
    neutrons: 64,
    shells: [2, 8, 18, 18, 2],
    atomicWeight: "112.41",
    electronConfiguration: "[Kr] 4d¹⁰ 5s²",
    title: "Cadmium (Cd) - The Battery Metal",
    description:
      "Cadmium is a soft, bluish-white metal similar to zinc. Its primary use has been in nickel-cadmium (NiCd) rechargeable batteries. It is also an excellent corrosion-resistant plating for steel. Due to its toxicity, its use is now declining.",
  },
  {
    name: "Indium",
    symbol: "In",
    protons: 49,
    neutrons: 66,
    shells: [2, 8, 18, 18, 3],
    atomicWeight: "114.82",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p¹",
    title: "Indium (In) - The Touchscreen Metal",
    description:
      "Indium is a very soft, silvery-white post-transition metal. Its most important compound is indium tin oxide (ITO), which is transparent and electrically conductive. This unique combination makes it essential for manufacturing touchscreens, LCDs, and solar panels.",
  },
  {
    name: "Tin",
    symbol: "Sn",
    protons: 50,
    neutrons: 69,
    shells: [2, 8, 18, 18, 4],
    atomicWeight: "118.71",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p²",
    title: "Tin (Sn) - The Ancient Alloy",
    description:
      "Tin is a silvery, malleable post-transition metal. It is best known as a component of bronze, an alloy with copper, which defined the Bronze Age. Today, its main use is in tin plating steel cans to prevent corrosion and as a component of solder.",
  },
  {
    name: "Antimony",
    symbol: "Sb",
    protons: 51,
    neutrons: 71,
    shells: [2, 8, 18, 18, 5],
    atomicWeight: "121.76",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p³",
    title: "Antimony (Sb) - The Flame Retardant",
    description:
      "Antimony is a lustrous gray metalloid. Its most significant use is in flame retardants, where it is added to plastics and textiles to prevent them from catching fire. It is also used to harden lead for batteries and bullets.",
  },
  {
    name: "Tellurium",
    symbol: "Te",
    protons: 52,
    neutrons: 76,
    shells: [2, 8, 18, 18, 6],
    atomicWeight: "127.60",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁴",
    title: "Tellurium (Te) - The Alloying Metalloid",
    description:
      "Tellurium is a brittle, silvery-white metalloid. It is a semiconductor and is often alloyed with other elements to improve their machinability or create specialized thermoelectric devices. It is one of the rarest stable solid elements on Earth.",
  },
  {
    name: "Iodine",
    symbol: "I",
    protons: 53,
    neutrons: 74,
    shells: [2, 8, 18, 18, 7],
    atomicWeight: "126.90",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁵",
    title: "Iodine (I) - The Essential Halogen",
    description:
      "Iodine is a lustrous, purple-black nonmetal that sublimes into a violet gas. It is an essential nutrient for humans, required for the synthesis of thyroid hormones. It is also used as a disinfectant (tincture of iodine) and in polarizing filters for LCDs.",
  },
  {
    name: "Xenon",
    symbol: "Xe",
    protons: 54,
    neutrons: 77,
    shells: [2, 8, 18, 18, 8],
    atomicWeight: "131.29",
    electronConfiguration: "[Kr] 4d¹⁰ 5s² 5p⁶",
    title: "Xenon (Xe) - The High-Intensity Light",
    description:
      "Xenon is a heavy, colorless, odorless noble gas. It is used in specialized light sources that produce a bright, white light similar to daylight, such as photographic flashes, movie projectors, and high-intensity car headlamps.",
  },
  {
    name: "Cesium",
    symbol: "Cs",
    protons: 55,
    neutrons: 78,
    shells: [2, 8, 18, 18, 8, 1],
    atomicWeight: "132.91",
    electronConfiguration: "[Xe] 6s¹",
    title: "Cesium (Cs) - The Most Reactive Metal",
    description:
      "Cesium is a soft, silvery-gold alkali metal that is liquid near room temperature. It is the most reactive and most electropositive of all stable elements, exploding on contact with water. Its most famous use is in atomic clocks, providing the modern definition of a second.",
  },
  {
    name: "Barium",
    symbol: "Ba",
    protons: 56,
    neutrons: 81,
    shells: [2, 8, 18, 18, 8, 2],
    atomicWeight: "137.33",
    electronConfiguration: "[Xe] 6s²",
    title: "Barium (Ba) - The Medical Imager",
    description:
      "Barium is a soft, silvery alkaline earth metal. Due to its high density, barium sulfate is opaque to X-rays and is used as a 'barium meal' to image the gastrointestinal tract in medicine. It also gives a pale green color to fireworks.",
  },
  {
    name: "Lanthanum",
    symbol: "La",
    protons: 57,
    neutrons: 82,
    shells: [2, 8, 18, 18, 9, 2],
    atomicWeight: "138.91",
    electronConfiguration: "[Xe] 5d¹ 6s²",
    title: "Lanthanum (La) - The Hidden Element",
    description:
      "Lanthanum is a soft, silvery-white metal that gives its name to the lanthanide series. It is used in high-quality camera lenses and optical glass to improve the refractive index. It's also found in the nickel-metal hydride batteries used in hybrid cars.",
  },
  {
    name: "Cerium",
    symbol: "Ce",
    protons: 58,
    neutrons: 82,
    shells: [2, 8, 18, 19, 9, 2],
    atomicWeight: "140.12",
    electronConfiguration: "[Xe] 4f¹ 5d¹ 6s²",
    title: "Cerium (Ce) - The Most Abundant Rare Earth",
    description:
      "Cerium is the most abundant of the rare-earth elements. It is a key component in the flint of lighters and is used as a polishing agent for glass and lenses (cerium oxide). It also acts as a catalyst in self-cleaning ovens.",
  },
  {
    name: "Praseodymium",
    symbol: "Pr",
    protons: 59,
    neutrons: 82,
    shells: [2, 8, 18, 21, 8, 2],
    atomicWeight: "140.91",
    electronConfiguration: "[Xe] 4f³ 6s²",
    title: "Praseodymium (Pr) - The Green Twin",
    description:
      "Praseodymium is a soft, silvery rare-earth metal. It is used with neodymium to create high-strength magnets. Its compounds produce a characteristic yellow-green color in glass and ceramics, often used in welder's goggles.",
  },
  {
    name: "Neodymium",
    symbol: "Nd",
    protons: 60,
    neutrons: 84,
    shells: [2, 8, 18, 22, 8, 2],
    atomicWeight: "144.24",
    electronConfiguration: "[Xe] 4f⁴ 6s²",
    title: "Neodymium (Nd) - The Super Magnet",
    description:
      "Neodymium is a silvery-white rare-earth metal. Its most important use is in creating neodymium magnets (NdFeB), the strongest type of permanent magnet known. These are critical for headphones, hard drives, electric motors, and wind turbines.",
  },
  {
    name: "Promethium",
    symbol: "Pm",
    protons: 61,
    neutrons: 84,
    shells: [2, 8, 18, 23, 8, 2],
    atomicWeight: "145",
    electronConfiguration: "[Xe] 4f⁵ 6s²",
    title: "Promethium (Pm) - The Luminous Paint",
    description:
      "Promethium is an extremely rare, radioactive rare-earth metal. All its isotopes are unstable. It is used in luminous paints for watches and signs that glow in the dark, and in specialized atomic batteries for spacecraft and missiles.",
  },
  {
    name: "Samarium",
    symbol: "Sm",
    protons: 62,
    neutrons: 90,
    shells: [2, 8, 18, 24, 8, 2],
    atomicWeight: "150.36",
    electronConfiguration: "[Xe] 4f⁶ 6s²",
    title: "Samarium (Sm) - The High-Temperature Magnet",
    description:
      "Samarium is a silvery-white rare-earth metal. It is used to create powerful samarium-cobalt magnets, which are notable for their ability to retain their magnetism at very high temperatures, making them useful in military and aerospace applications.",
  },
  {
    name: "Europium",
    symbol: "Eu",
    protons: 63,
    neutrons: 90,
    shells: [2, 8, 18, 25, 8, 2],
    atomicWeight: "151.96",
    electronConfiguration: "[Xe] 4f⁷ 6s²",
    title: "Europium (Eu) - The Red and Blue Phosphor",
    description:
      "Europium is a moderately hard, silvery rare-earth metal. It is brilliantly fluorescent, making it crucial as the red and blue phosphors in television screens and fluorescent lamps. It is also used in anti-counterfeiting phosphors in Euro banknotes.",
  },
  {
    name: "Gadolinium",
    symbol: "Gd",
    protons: 64,
    neutrons: 94,
    shells: [2, 8, 18, 25, 9, 2],
    atomicWeight: "157.25",
    electronConfiguration: "[Xe] 4f⁷ 5d¹ 6s²",
    title: "Gadolinium (Gd) - The MRI Contrast Agent",
    description:
      "Gadolinium is a silvery-white rare-earth metal that is ferromagnetic at low temperatures. Its compounds are highly effective as contrast agents in MRI scans, enhancing the visibility of tumors and tissues. It also has the highest neutron-capture cross-section of any stable element.",
  },
  {
    name: "Terbium",
    symbol: "Tb",
    protons: 65,
    neutrons: 94,
    shells: [2, 8, 18, 27, 8, 2],
    atomicWeight: "158.93",
    electronConfiguration: "[Xe] 4f⁹ 6s²",
    title: "Terbium (Tb) - The Green Phosphor",
    description:
      "Terbium is a silvery-white rare-earth metal that is soft enough to be cut with a knife. It is used as the green phosphor in CRT screens and fluorescent lamps. It's also a component of Terfenol-D, an alloy that changes shape in a magnetic field, used in naval sonar systems.",
  },
  {
    name: "Dysprosium",
    symbol: "Dy",
    protons: 66,
    neutrons: 97,
    shells: [2, 8, 18, 28, 8, 2],
    atomicWeight: "162.50",
    electronConfiguration: "[Xe] 4f¹⁰ 6s²",
    title: "Dysprosium (Dy) - The Magnet Additive",
    description:
      "Dysprosium is a rare-earth metal with a bright silver luster. Its primary use is as an additive in neodymium magnets to help them resist demagnetization at high temperatures, which is critical for electric vehicle motors and wind turbines.",
  },
  {
    name: "Holmium",
    symbol: "Ho",
    protons: 67,
    neutrons: 98,
    shells: [2, 8, 18, 29, 8, 2],
    atomicWeight: "164.93",
    electronConfiguration: "[Xe] 4f¹¹ 6s²",
    title: "Holmium (Ho) - The Magnetic Concentrator",
    description:
      "Holmium is a bright, soft, silvery rare-earth metal. It has the highest magnetic strength of any element, which allows it to be used to create the pole pieces of the strongest static magnets. Its compounds are used to color glass yellow or red.",
  },
  {
    name: "Erbium",
    symbol: "Er",
    protons: 68,
    neutrons: 99,
    shells: [2, 8, 18, 30, 8, 2],
    atomicWeight: "167.26",
    electronConfiguration: "[Xe] 4f¹² 6s²",
    title: "Erbium (Er) - The Fiber Optic Amplifier",
    description:
      "Erbium is a silvery-white solid rare-earth metal. Its most important application is in erbium-doped fiber amplifiers (EDFAs), which boost the signal in long-distance fiber optic cables, forming the backbone of the internet.",
  },
  {
    name: "Thulium",
    symbol: "Tm",
    protons: 69,
    neutrons: 100,
    shells: [2, 8, 18, 31, 8, 2],
    atomicWeight: "168.93",
    electronConfiguration: "[Xe] 4f¹³ 6s²",
    title: "Thulium (Tm) - The Portable X-ray Source",
    description:
      "Thulium is the least abundant of the stable rare-earth elements. When bombarded with neutrons in a reactor, it produces an isotope that emits X-rays, making it useful in portable X-ray devices for medical and industrial purposes.",
  },
  {
    name: "Ytterbium",
    symbol: "Yb",
    protons: 70,
    neutrons: 103,
    shells: [2, 8, 18, 32, 8, 2],
    atomicWeight: "173.05",
    electronConfiguration: "[Xe] 4f¹⁴ 6s²",
    title: "Ytterbium (Yb) - The Steel Improver",
    description:
      "Ytterbium is a soft, silvery rare-earth metal. It is used to improve the grain refinement, strength, and other mechanical properties of stainless steel. It is also a potential component of highly accurate atomic clocks.",
  },
  {
    name: "Lutetium",
    symbol: "Lu",
    protons: 71,
    neutrons: 104,
    shells: [2, 8, 18, 32, 9, 2],
    atomicWeight: "174.97",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹ 6s²",
    title: "Lutetium (Lu) - The Final Lanthanide",
    description:
      "Lutetium is the last element in the lanthanide series. It is a very rare and expensive silvery-white metal. Its uses are limited, but its radioactive isotopes can be used in cancer therapy, and it serves as a catalyst in certain industrial processes.",
  },
  {
    name: "Hafnium",
    symbol: "Hf",
    protons: 72,
    neutrons: 106,
    shells: [2, 8, 18, 32, 10, 2],
    atomicWeight: "178.49",
    electronConfiguration: "[Xe] 4f¹⁴ 5d² 6s²",
    title: "Hafnium (Hf) - The Neutron Absorber",
    description:
      "Hafnium is a lustrous, silvery-gray transition metal. It is chemically similar to zirconium and is found in the same minerals. Its excellent ability to absorb neutrons makes it ideal for use in control rods in nuclear submarines.",
  },
  {
    name: "Tantalum",
    symbol: "Ta",
    protons: 73,
    neutrons: 108,
    shells: [2, 8, 18, 32, 11, 2],
    atomicWeight: "180.95",
    electronConfiguration: "[Xe] 4f¹⁴ 5d³ 6s²",
    title: "Tantalum (Ta) - The Capacitor Metal",
    description:
      "Tantalum is a rare, hard, blue-gray transition metal that is highly corrosion-resistant. Its main use is in producing tantalum capacitors, which are small, reliable, and essential components in mobile phones, laptops, and other electronics.",
  },
  {
    name: "Tungsten",
    symbol: "W",
    protons: 74,
    neutrons: 110,
    shells: [2, 8, 18, 32, 12, 2],
    atomicWeight: "183.84",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁴ 6s²",
    title: "Tungsten (W) - The Highest Melting Point",
    description:
      "Tungsten has the highest melting point of all metallic elements. This property makes it perfect for the filaments in incandescent light bulbs. It is also extremely dense and hard, used in armor-piercing ammunition and industrial cutting tools (tungsten carbide).",
  },
  {
    name: "Rhenium",
    symbol: "Re",
    protons: 75,
    neutrons: 111,
    shells: [2, 8, 18, 32, 13, 2],
    atomicWeight: "186.21",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁵ 6s²",
    title: "Rhenium (Re) - The Jet Engine Superalloy",
    description:
      "Rhenium is a silvery-white, heavy, and rare transition metal. It has one of the highest melting points. Its primary use is in high-temperature superalloys for making turbine blades and exhaust nozzles in jet engines.",
  },
  {
    name: "Osmium",
    symbol: "Os",
    protons: 76,
    neutrons: 114,
    shells: [2, 8, 18, 32, 14, 2],
    atomicWeight: "190.23",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁶ 6s²",
    title: "Osmium (Os) - The Densest Element",
    description:
      "Osmium is the densest naturally occurring element. It is a hard, brittle, blue-white transition metal. Due to its hardness and durability, it is used in alloys for fountain pen tips, electrical contacts, and other applications where extreme wear resistance is needed.",
  },
  {
    name: "Iridium",
    symbol: "Ir",
    protons: 77,
    neutrons: 115,
    shells: [2, 8, 18, 32, 15, 2],
    atomicWeight: "192.22",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁷ 6s²",
    title: "Iridium (Ir) - The Most Corrosion-Resistant",
    description:
      "Iridium is a very hard, brittle, silvery-white metal from the platinum group. It is considered the most corrosion-resistant metal known. It is used in high-performance spark plugs, crucibles for growing crystals, and was used to coat the Voyager spacecraft's fuel tanks.",
  },
  {
    name: "Platinum",
    symbol: "Pt",
    protons: 78,
    neutrons: 117,
    shells: [2, 8, 18, 32, 17, 1],
    atomicWeight: "195.08",
    electronConfiguration: "[Xe] 4f¹⁴ 5d⁹ 6s¹",
    title: "Platinum (Pt) - The Precious Catalyst",
    description:
      "Platinum is a dense, malleable, and highly unreactive precious metal. It is prized in jewelry for its beauty and resistance to tarnish. It is also a vital industrial material, used extensively in catalytic converters, laboratory equipment, and medical devices.",
  },
  {
    name: "Gold",
    symbol: "Au",
    protons: 79,
    neutrons: 118,
    shells: [2, 8, 18, 32, 18, 1],
    atomicWeight: "196.97",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
    title: "Gold (Au) - The Eternal Metal",
    description:
      "Gold is a bright, slightly reddish-yellow, dense, and soft precious metal. Valued since antiquity for its beauty, rarity, and resistance to corrosion, it is used for coinage, jewelry, and as a financial standard. It is also an excellent electrical conductor used in high-end electronics.",
  },
  {
    name: "Mercury",
    symbol: "Hg",
    protons: 80,
    neutrons: 121,
    shells: [2, 8, 18, 32, 18, 2],
    atomicWeight: "200.59",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
    title: "Mercury (Hg) - The Liquid Metal",
    description:
      "Mercury is the only metallic element that is liquid at standard conditions for temperature and pressure. This silvery-white metal is used in thermometers, barometers, and fluorescent lighting. It is highly toxic, and its use is now heavily restricted.",
  },
  {
    name: "Thallium",
    symbol: "Tl",
    protons: 81,
    neutrons: 123,
    shells: [2, 8, 18, 32, 18, 3],
    atomicWeight: "204.38",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
    title: "Thallium (Tl) - The Poisoner's Poison",
    description:
      "Thallium is a soft, grayish post-transition metal that resembles tin but discolors on exposure to air. It is extremely toxic and was historically used as a rat poison and insecticide, but this is now banned in most countries. It has niche uses in electronics and optics.",
  },
  {
    name: "Lead",
    symbol: "Pb",
    protons: 82,
    neutrons: 125,
    shells: [2, 8, 18, 32, 18, 4],
    atomicWeight: "207.2",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
    title: "Lead (Pb) - The Dense Shield",
    description:
      "Lead is a heavy, soft, and malleable post-transition metal. Its high density makes it an excellent shield against radiation (X-rays and gamma rays). It is the primary component of lead-acid batteries used in cars. Its use has been reduced due to its toxicity.",
  },
  {
    name: "Bismuth",
    symbol: "Bi",
    protons: 83,
    neutrons: 126,
    shells: [2, 8, 18, 32, 18, 5],
    atomicWeight: "208.98",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
    title: "Bismuth (Bi) - The Non-Toxic Heavy Metal",
    description:
      "Bismuth is a brittle, silvery-white metal with a pinkish tinge due to an oxide layer. It is unusually non-toxic for a heavy metal and is used in stomach-soothing remedies like Pepto-Bismol. Its alloys have low melting points, used in fuses and fire sprinklers.",
  },
  {
    name: "Polonium",
    symbol: "Po",
    protons: 84,
    neutrons: 125,
    shells: [2, 8, 18, 32, 18, 6],
    atomicWeight: "209",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
    title: "Polonium (Po) - The Radioactive Toxin",
    description:
      "Polonium is a rare and highly radioactive metalloid. It is intensely toxic, even in minute amounts. It has been used as a source of alpha particles in scientific research and, controversially, as a poison. It is also used to eliminate static electricity in industrial settings.",
  },
  {
    name: "Astatine",
    symbol: "At",
    protons: 85,
    neutrons: 125,
    shells: [2, 8, 18, 32, 18, 7],
    atomicWeight: "210",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
    title: "Astatine (At) - The Rarest Element",
    description:
      "Astatine is the rarest naturally occurring element on Earth. It is a highly radioactive halogen. All its isotopes are short-lived, making it extremely difficult to study. It is being researched for use in targeted alpha-particle therapy for cancer.",
  },
  {
    name: "Radon",
    symbol: "Rn",
    protons: 86,
    neutrons: 136,
    shells: [2, 8, 18, 32, 18, 8],
    atomicWeight: "222",
    electronConfiguration: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
    title: "Radon (Rn) - The Radioactive Noble Gas",
    description:
      "Radon is a colorless, odorless, and radioactive noble gas. It is formed from the natural decay of uranium in soil and rock. It can accumulate in buildings and is a significant cause of lung cancer. Medically, it has been used in radiation therapy.",
  },
  {
    name: "Francium",
    symbol: "Fr",
    protons: 87,
    neutrons: 136,
    shells: [2, 8, 18, 32, 18, 8, 1],
    atomicWeight: "223",
    electronConfiguration: "[Rn] 7s¹",
    title: "Francium (Fr) - The Most Unstable",
    description:
      "Francium is the second-rarest naturally occurring element, after astatine. It is an extremely unstable alkali metal with a half-life of only 22 minutes for its longest-lived isotope. Due to its instability and rarity, it has no commercial applications.",
  },
  {
    name: "Radium",
    symbol: "Ra",
    protons: 88,
    neutrons: 138,
    shells: [2, 8, 18, 32, 18, 8, 2],
    atomicWeight: "226",
    electronConfiguration: "[Rn] 7s²",
    title: "Radium (Ra) - The Luminous Danger",
    description:
      "Radium is a silvery-white, highly radioactive alkaline earth metal. It was famously used in self-luminous paints for watches and dials until its health risks became known. It was discovered by Marie and Pierre Curie and played a key role in the development of radiotherapy.",
  },
  {
    name: "Actinium",
    symbol: "Ac",
    protons: 89,
    neutrons: 138,
    shells: [2, 8, 18, 32, 18, 9, 2],
    atomicWeight: "227",
    electronConfiguration: "[Rn] 6d¹ 7s²",
    title: "Actinium (Ac) - The Prototypical Actinide",
    description:
      "Actinium is a soft, silvery-white radioactive metal that gives its name to the actinide series. It is about 150 times as radioactive as radium. Its intense radioactivity makes it a valuable neutron source, but it has few other industrial uses.",
  },
  {
    name: "Thorium",
    symbol: "Th",
    protons: 90,
    neutrons: 142,
    shells: [2, 8, 18, 32, 18, 10, 2],
    atomicWeight: "232.04",
    electronConfiguration: "[Rn] 6d² 7s²",
    title: "Thorium (Th) - The Potential Nuclear Fuel",
    description:
      "Thorium is a weakly radioactive, silvery metal. It is much more abundant than uranium and is being investigated as a safer and more efficient alternative fuel for nuclear reactors. It is also used in high-quality optics and gas mantles.",
  },
  {
    name: "Protactinium",
    symbol: "Pa",
    protons: 91,
    neutrons: 140,
    shells: [2, 8, 18, 32, 20, 9, 2],
    atomicWeight: "231.04",
    electronConfiguration: "[Rn] 5f² 6d¹ 7s²",
    title: "Protactinium (Pa) - The Elusive Actinide",
    description:
      "Protactinium is a dense, silvery-gray radioactive actinide. It is one of the rarest and most expensive naturally occurring elements. Due to its scarcity, toxicity, and high radioactivity, it currently has no uses outside of basic scientific research.",
  },
  {
    name: "Uranium",
    symbol: "U",
    protons: 92,
    neutrons: 146,
    shells: [2, 8, 18, 32, 21, 9, 2],
    atomicWeight: "238.03",
    electronConfiguration: "[Rn] 5f³ 6d¹ 7s²",
    title: "Uranium (U) - The Fuel of Fission",
    description:
      "Uranium is a silvery-gray, weakly radioactive metal. It is the primary fuel for nuclear reactors and the main material for nuclear weapons. Its high density also makes it useful as a counterweight in aircraft and in armor-piercing projectiles.",
  },
  {
    name: "Neptunium",
    symbol: "Np",
    protons: 93,
    neutrons: 144,
    shells: [2, 8, 18, 32, 22, 9, 2],
    atomicWeight: "237",
    electronConfiguration: "[Rn] 5f⁴ 6d¹ 7s²",
    title: "Neptunium (Np) - The First Transuranic",
    description:
      "Neptunium is the first transuranic element, meaning it has an atomic number greater than uranium. It is a radioactive, silvery actinide. It is primarily a byproduct of nuclear reactor operation and has some use in neutron detection instruments.",
  },
  {
    name: "Plutonium",
    symbol: "Pu",
    protons: 94,
    neutrons: 150,
    shells: [2, 8, 18, 32, 24, 8, 2],
    atomicWeight: "244",
    electronConfiguration: "[Rn] 5f⁶ 7s²",
    title: "Plutonium (Pu) - The Nuclear Powerhouse",
    description:
      "Plutonium is a radioactive actinide metal. It is the primary fissile isotope used in most modern nuclear weapons. It is also used as a fuel in some nuclear reactors and as a long-lived power source for deep space probes like the New Horizons mission to Pluto.",
  },
  {
    name: "Americium",
    symbol: "Am",
    protons: 95,
    neutrons: 148,
    shells: [2, 8, 18, 32, 25, 8, 2],
    atomicWeight: "243",
    electronConfiguration: "[Rn] 5f⁷ 7s²",
    title: "Americium (Am) - The Smoke Detector",
    description:
      "Americium is a synthetic radioactive element. Its most common application is in household smoke detectors, where a tiny amount of americium-241 emits alpha particles that ionize the air, allowing a small current to flow. Smoke disrupts this current, triggering the alarm.",
  },
  {
    name: "Curium",
    symbol: "Cm",
    protons: 96,
    neutrons: 151,
    shells: [2, 8, 18, 32, 25, 9, 2],
    atomicWeight: "247",
    electronConfiguration: "[Rn] 5f⁷ 6d¹ 7s²",
    title: "Curium (Cm) - The Alpha Emitter",
    description:
      "Curium is a hard, dense, silvery radioactive element named after Marie and Pierre Curie. It is a powerful alpha-particle emitter and has been used as a power source in radioisotope thermoelectric generators (RTGs) for spacecraft and pacemakers.",
  },
  {
    name: "Berkelium",
    symbol: "Bk",
    protons: 97,
    neutrons: 150,
    shells: [2, 8, 18, 32, 27, 8, 2],
    atomicWeight: "247",
    electronConfiguration: "[Rn] 5f⁹ 7s²",
    title: "Berkelium (Bk) - The Research Element",
    description:
      "Berkelium is a synthetic radioactive element named after Berkeley, California, the home of the lab where it was discovered. It is produced in minute quantities and is used almost exclusively for scientific research, particularly for synthesizing heavier elements.",
  },
  {
    name: "Californium",
    symbol: "Cf",
    protons: 98,
    neutrons: 153,
    shells: [2, 8, 18, 32, 28, 8, 2],
    atomicWeight: "251",
    electronConfiguration: "[Rn] 5f¹⁰ 7s²",
    title: "Californium (Cf) - The Neutron Source",
    description:
      "Californium is a radioactive element named after the state of California. It is a very strong neutron emitter, with one microgram emitting 170 million neutrons per minute. This makes it useful for starting up nuclear reactors and in cancer treatment.",
  },
  {
    name: "Einsteinium",
    symbol: "Es",
    protons: 99,
    neutrons: 153,
    shells: [2, 8, 18, 32, 29, 8, 2],
    atomicWeight: "252",
    electronConfiguration: "[Rn] 5f¹¹ 7s²",
    title: "Einsteinium (Es) - Tribute to a Genius",
    description:
      "Einsteinium is a synthetic element named after Albert Einstein. It was discovered in the debris of the first hydrogen bomb explosion. It is highly radioactive and has only ever been produced in tiny amounts, used solely for scientific research.",
  },
  {
    name: "Fermium",
    symbol: "Fm",
    protons: 100,
    neutrons: 157,
    shells: [2, 8, 18, 32, 30, 8, 2],
    atomicWeight: "257",
    electronConfiguration: "[Rn] 5f¹² 7s²",
    title: "Fermium (Fm) - The 100th Element",
    description:
      "Fermium, the 100th element on the periodic table, is named after Enrico Fermi. Like einsteinium, it was discovered in the fallout of the first hydrogen bomb test. It cannot be created in large quantities and has no applications beyond basic research.",
  },
  {
    name: "Mendelevium",
    symbol: "Md",
    protons: 101,
    neutrons: 157,
    shells: [2, 8, 18, 32, 31, 8, 2],
    atomicWeight: "258",
    electronConfiguration: "[Rn] 5f¹³ 7s²",
    title: "Mendelevium (Md) - Honoring the Table's Architect",
    description:
      "Mendelevium is named after Dmitri Mendeleev, the father of the periodic table. It was the first element to be synthesized one atom at a time. It is a highly radioactive synthetic element used only to study its own chemical properties.",
  },
  {
    name: "Nobelium",
    symbol: "No",
    protons: 102,
    neutrons: 157,
    shells: [2, 8, 18, 32, 32, 8, 2],
    atomicWeight: "259",
    electronConfiguration: "[Rn] 5f¹⁴ 7s²",
    title: "Nobelium (No) - Named for Nobel",
    description:
      "Nobelium is a synthetic element named in honor of Alfred Nobel. Its discovery was complex and claimed by multiple labs. It is a transuranic element whose chemical properties are still being explored, one atom at a time.",
  },
  {
    name: "Lawrencium",
    symbol: "Lr",
    protons: 103,
    neutrons: 159,
    shells: [2, 8, 18, 32, 32, 8, 3],
    atomicWeight: "262",
    electronConfiguration: "[Rn] 5f¹⁴ 7s² 7p¹",
    title: "Lawrencium (Lr) - The Final Actinide",
    description:
      "Lawrencium is a synthetic radioactive element and the final member of the actinide series. It is named after Ernest Lawrence, inventor of the cyclotron particle accelerator. Its chemical properties are difficult to study due to its extremely short half-life.",
  },
  {
    name: "Rutherfordium",
    symbol: "Rf",
    protons: 104,
    neutrons: 161,
    shells: [2, 8, 18, 32, 32, 10, 2],
    atomicWeight: "267",
    electronConfiguration: "[Rn] 5f¹⁴ 6d² 7s²",
    title: "Rutherfordium (Rf) - The First Transactinide",
    description:
      "Rutherfordium is the first transactinide element, named after Ernest Rutherford. It is a highly radioactive, synthetic element whose properties are predicted to be similar to hafnium. Only a few hundred atoms have ever been made.",
  },
  {
    name: "Dubnium",
    symbol: "Db",
    protons: 105,
    neutrons: 163,
    shells: [2, 8, 18, 32, 32, 11, 2],
    atomicWeight: "268",
    electronConfiguration: "[Rn] 5f¹⁴ 6d³ 7s²",
    title: "Dubnium (Db) - From the Joint Institute",
    description:
      "Dubnium is a synthetic element named after Dubna, Russia, home of the Joint Institute for Nuclear Research. It is extremely unstable, with its most stable isotope having a half-life of just over a day. It has no uses outside of research.",
  },
  {
    name: "Seaborgium",
    symbol: "Sg",
    protons: 106,
    neutrons: 165,
    shells: [2, 8, 18, 32, 32, 12, 2],
    atomicWeight: "269",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁴ 7s²",
    title: "Seaborgium (Sg) - Named for a Living Person",
    description:
      "Seaborgium is a synthetic element named after Glenn T. Seaborg, a key figure in synthesizing many transuranic elements. It was the first element to be named after a living person. Its chemistry is predicted to resemble tungsten.",
  },
  {
    name: "Bohrium",
    symbol: "Bh",
    protons: 107,
    neutrons: 165,
    shells: [2, 8, 18, 32, 32, 13, 2],
    atomicWeight: "270",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁵ 7s²",
    title: "Bohrium (Bh) - Honoring Niels Bohr",
    description:
      "Bohrium is a synthetic element named in honor of Niels Bohr, a pioneer of quantum mechanics. It is a superheavy element whose most stable known isotope has a half-life of about one minute. It is expected to behave like other group 7 elements.",
  },
  {
    name: "Hassium",
    symbol: "Hs",
    protons: 108,
    neutrons: 169,
    shells: [2, 8, 18, 32, 32, 14, 2],
    atomicWeight: "269",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁶ 7s²",
    title: "Hassium (Hs) - From Hesse, Germany",
    description:
      "Hassium is named after the German state of Hesse, where it was first synthesized. It is a synthetic, radioactive element with chemical properties predicted to be similar to osmium. Its most stable isotope has a half-life of about 10 seconds.",
  },
  {
    name: "Meitnerium",
    symbol: "Mt",
    protons: 109,
    neutrons: 169,
    shells: [2, 8, 18, 32, 32, 15, 2],
    atomicWeight: "278",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁷ 7s²",
    title: "Meitnerium (Mt) - Honoring Lise Meitner",
    description:
      "Meitnerium is a synthetic element named to honor Lise Meitner, a physicist who was a key part of the team that discovered nuclear fission. It is an extremely radioactive element of which only a few atoms have ever been synthesized.",
  },
  {
    name: "Darmstadtium",
    symbol: "Ds",
    protons: 110,
    neutrons: 171,
    shells: [2, 8, 18, 32, 32, 16, 2],
    atomicWeight: "281",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁸ 7s²",
    title: "Darmstadtium (Ds) - The GSI Element",
    description:
      "Darmstadtium is named after Darmstadt, Germany, the city where it was created at the GSI Helmholtz Centre for Heavy Ion Research. It is a synthetic, super-heavy element with properties expected to be similar to platinum.",
  },
  {
    name: "Roentgenium",
    symbol: "Rg",
    protons: 111,
    neutrons: 171,
    shells: [2, 8, 18, 32, 32, 17, 2],
    atomicWeight: "282",
    electronConfiguration: "[Rn] 5f¹⁴ 6d⁹ 7s²",
    title: "Roentgenium (Rg) - For the Discoverer of X-rays",
    description:
      "Roentgenium is a synthetic element named in honor of Wilhelm Conrad Röntgen, the discoverer of X-rays. It is extremely unstable, and its most stable known isotope has a half-life of about 26 seconds. It is predicted to be a noble metal like gold.",
  },
  {
    name: "Copernicium",
    symbol: "Cn",
    protons: 112,
    neutrons: 173,
    shells: [2, 8, 18, 32, 32, 18, 2],
    atomicWeight: "285",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
    title: "Copernicium (Cn) - Honoring Copernicus",
    description:
      "Copernicium is a synthetic element named after the astronomer Nicolaus Copernicus. It is a super-heavy element that is extremely volatile for its mass, with some predictions suggesting it could be a liquid or a gas at room temperature.",
  },
  {
    name: "Nihonium",
    symbol: "Nh",
    protons: 113,
    neutrons: 171,
    shells: [2, 8, 18, 32, 32, 18, 3],
    atomicWeight: "286",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
    title: "Nihonium (Nh) - From Japan",
    description:
      "Nihonium is a synthetic element named after the Japanese word for Japan, 'Nihon'. It was the first modern element to be discovered in an Asian country. It is a super-heavy, extremely radioactive element whose properties are largely unknown.",
  },
  {
    name: "Flerovium",
    symbol: "Fl",
    protons: 114,
    neutrons: 175,
    shells: [2, 8, 18, 32, 32, 18, 4],
    atomicWeight: "289",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
    title: "Flerovium (Fl) - From the Flerov Laboratory",
    description:
      "Flerovium is named after the Flerov Laboratory of Nuclear Reactions in Dubna, Russia. It is a super-heavy synthetic element located in an 'island of stability,' a theoretical region where super-heavy elements are predicted to have longer half-lives.",
  },
  {
    name: "Moscovium",
    symbol: "Mc",
    protons: 115,
    neutrons: 173,
    shells: [2, 8, 18, 32, 32, 18, 5],
    atomicWeight: "289",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
    title: "Moscovium (Mc) - From the Moscow Oblast",
    description:
      "Moscovium is a synthetic, super-heavy element named for the Moscow Oblast, where the Joint Institute for Nuclear Research is located. It is extremely radioactive, and its limited production precludes any use outside of scientific study.",
  },
  {
    name: "Livermorium",
    symbol: "Lv",
    protons: 116,
    neutrons: 177,
    shells: [2, 8, 18, 32, 32, 18, 6],
    atomicWeight: "293",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
    title: "Livermorium (Lv) - A Collaborative Discovery",
    description:
      "Livermorium is named after the Lawrence Livermore National Laboratory in California, which collaborated with Russian scientists on its discovery. It is a synthetic, super-heavy element with a half-life measured in tens of milliseconds.",
  },
  {
    name: "Tennessine",
    symbol: "Ts",
    protons: 117,
    neutrons: 177,
    shells: [2, 8, 18, 32, 32, 18, 7],
    atomicWeight: "294",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
    title: "Tennessine (Ts) - Honoring Tennessee",
    description:
      "Tennessine is a synthetic super-heavy element named to honor the state of Tennessee, home to several key research laboratories. As a member of group 17, it is predicted to be a halogen, though its properties may differ significantly from lighter halogens.",
  },
  {
    name: "Oganesson",
    symbol: "Og",
    protons: 118,
    neutrons: 176,
    shells: [2, 8, 18, 32, 32, 18, 8],
    atomicWeight: "294",
    electronConfiguration: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
    title: "Oganesson (Og) - The Heaviest Element",
    description:
      "Oganesson is the element with the highest atomic number and atomic mass ever synthesized. It is named after Yuri Oganessian for his pioneering research in super-heavy elements. Though in group 18, it may not be a noble gas and is predicted to be a solid semiconductor at room temperature.",
  },
];
